/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current account's application trackers */
        get: operations["list_applications_api_v1_applications_get"];
        put?: never;
        /** Start tracking a job application */
        post: operations["create_application_api_v1_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an application tracker and its status history */
        get: operations["get_application_api_v1_applications__application_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Move an application to an allowed next status */
        patch: operations["transition_application_api_v1_applications__application_id__status_patch"];
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the verified current account */
        get: operations["get_current_account_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check API liveness */
        get: operations["liveness_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check API readiness */
        get: operations["readiness_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search configured job providers */
        post: operations["search_jobs_api_v1_jobs_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/search-tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an asynchronous job-discovery task */
        post: operations["create_search_task_api_v1_jobs_search_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/search-tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll an asynchronous job-discovery task */
        get: operations["get_search_task_api_v1_jobs_search_tasks__task_id__get"];
        put?: never;
        post?: never;
        /** Request cancellation of an asynchronous job search */
        delete: operations["cancel_search_task_api_v1_jobs_search_tasks__task_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a job returned by this API process */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rank discovered jobs against a reviewed resume */
        post: operations["recommend_jobs_api_v1_recommendations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the signed-in user's current resume profile */
        get: operations["get_current_resume_api_v1_resumes_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse a resume */
        post: operations["parse_resume_api_v1_resumes_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/saved-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current account's saved jobs */
        get: operations["list_saved_jobs_api_v1_saved_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/saved-jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save or update a job for the current account */
        put: operations["save_job_api_v1_saved_jobs__job_id__put"];
        post?: never;
        /** Remove a saved job from the current account */
        delete: operations["remove_saved_job_api_v1_saved_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApplicationDetailResponse */
        ApplicationDetailResponse: {
            /**
             * Allowed Next Statuses
             * @default []
             */
            allowed_next_statuses: components["schemas"]["ApplicationStatus"][];
            /** Applied At */
            applied_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Events
             * @default []
             */
            events: components["schemas"]["ApplicationEventResponse"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            job: components["schemas"]["JobResponse"];
            /** Next Action */
            next_action?: string | null;
            /** Next Action Due At */
            next_action_due_at?: string | null;
            /** Notes */
            notes?: string | null;
            /** Resume Id */
            resume_id?: string | null;
            status: components["schemas"]["ApplicationStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ApplicationEventResponse */
        ApplicationEventResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            new_status: components["schemas"]["ApplicationStatus"];
            /** Note */
            note?: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            previous_status: components["schemas"]["ApplicationStatus"] | null;
        };
        /** ApplicationListResponse */
        ApplicationListResponse: {
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["ApplicationResponse"][];
        };
        /** ApplicationResponse */
        ApplicationResponse: {
            /**
             * Allowed Next Statuses
             * @default []
             */
            allowed_next_statuses: components["schemas"]["ApplicationStatus"][];
            /** Applied At */
            applied_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            job: components["schemas"]["JobResponse"];
            /** Next Action */
            next_action?: string | null;
            /** Next Action Due At */
            next_action_due_at?: string | null;
            /** Notes */
            notes?: string | null;
            /** Resume Id */
            resume_id?: string | null;
            status: components["schemas"]["ApplicationStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ApplicationStatus
         * @description User-visible stages in the assisted application workflow.
         * @enum {string}
         */
        ApplicationStatus: "Discovered" | "Saved" | "Preparing" | "Ready to apply" | "Applied" | "Assessment" | "Interview" | "Offer" | "Rejected" | "Withdrawn";
        /** AuthenticatedUserResponse */
        AuthenticatedUserResponse: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * BackgroundTaskStatus
         * @description Durable lifecycle states for background work.
         * @enum {string}
         */
        BackgroundTaskStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /** Body_parse_resume_api_v1_resumes_parse_post */
        Body_parse_resume_api_v1_resumes_parse_post: {
            /**
             * File
             * @description PDF, DOCX, or UTF-8 text resume
             */
            file: string;
        };
        /** CreateApplicationRequest */
        CreateApplicationRequest: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Next Action */
            next_action?: string | null;
            /** Next Action Due At */
            next_action_due_at?: string | null;
            /** Notes */
            notes?: string | null;
            /** Resume Id */
            resume_id?: string | null;
        };
        /**
         * DatePosted
         * @description Portable date filters supported by job discovery.
         * @enum {string}
         */
        DatePosted: "all" | "today" | "3days" | "week" | "month";
        /**
         * EmploymentType
         * @description Supported employment types.
         * @enum {string}
         */
        EmploymentType: "Full Time" | "Part Time" | "Internship" | "Contract" | "Remote";
        /** ErrorResponse */
        ErrorResponse: {
            /** Code */
            code: string;
            /**
             * Details
             * @default []
             */
            details: components["schemas"]["ValidationIssue"][];
            /** Message */
            message: string;
        };
        /**
         * ExperienceLevel
         * @description Supported job experience levels.
         * @enum {string}
         */
        ExperienceLevel: "Entry" | "Mid" | "Senior" | "Lead" | "Principal";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Stable response returned by liveness and readiness probes.
         */
        HealthResponse: {
            /** Checks */
            checks?: {
                [key: string]: string;
            };
            /** Service */
            service: string;
            status: components["schemas"]["HealthStatus"];
            /** Version */
            version: string;
        };
        /**
         * HealthStatus
         * @enum {string}
         */
        HealthStatus: "ok" | "ready" | "not_ready";
        /** JobRecommendationResponse */
        JobRecommendationResponse: {
            assessment: components["schemas"]["MatchAssessmentResponse"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Rank */
            rank?: number | null;
        };
        /** JobResponse */
        JobResponse: {
            /** Company */
            company: string;
            /** Description */
            description: string;
            employment_type: components["schemas"]["EmploymentType"];
            experience_level: components["schemas"]["ExperienceLevel"];
            /** External Id */
            external_id?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Location */
            location: string;
            /**
             * Required Skills
             * @default []
             */
            required_skills: components["schemas"]["SkillResponse"][];
            source: components["schemas"]["JobSource"];
            /** Source Name */
            source_name?: string | null;
            /** Source Url */
            source_url?: string | null;
            /** Title */
            title: string;
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** JobSearchRequest */
        JobSearchRequest: {
            /** Country */
            country?: string | null;
            /** @default all */
            date_posted: components["schemas"]["DatePosted"];
            /**
             * Employment Types
             * @default []
             */
            employment_types: components["schemas"]["EmploymentType"][];
            /** Location */
            location: string;
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Page Size
             * @default 20
             */
            page_size: number;
            /** Remote Only */
            remote_only?: boolean | null;
            /** Role */
            role: string;
        };
        /** JobSearchResponse */
        JobSearchResponse: {
            /**
             * Jobs
             * @default []
             */
            jobs: components["schemas"]["JobResponse"][];
            /**
             * Provider Failures
             * @default []
             */
            provider_failures: components["schemas"]["ProviderFailureResponse"][];
            /** Providers Attempted */
            providers_attempted: number;
            /** Providers Succeeded */
            providers_succeeded: number;
            status: components["schemas"]["JobSearchStatus"];
        };
        /**
         * JobSearchStatus
         * @enum {string}
         */
        JobSearchStatus: "complete" | "partial" | "failed";
        /** JobSearchTaskCreatedResponse */
        JobSearchTaskCreatedResponse: {
            /** Access Token */
            access_token: string;
            status: components["schemas"]["BackgroundTaskStatus"];
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
        };
        /** JobSearchTaskResponse */
        JobSearchTaskResponse: {
            /** Attempt Count */
            attempt_count: number;
            /**
             * Cancellation Requested
             * @default false
             */
            cancellation_requested: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Code */
            error_code?: string | null;
            /** Max Attempts */
            max_attempts: number;
            result?: components["schemas"]["JobSearchResponse"] | null;
            status: components["schemas"]["BackgroundTaskStatus"];
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * JobSource
         * @description Supported job providers.
         * @enum {string}
         */
        JobSource: "JSearch" | "Adzuna" | "Arbeitnow" | "The Muse" | "Workday" | "Greenhouse" | "SmartRecruiters" | "Ashby" | "Lever" | "Company" | "Other";
        /** MatchAssessmentResponse */
        MatchAssessmentResponse: {
            /** Algorithm Version */
            algorithm_version: string;
            /**
             * Components
             * @default []
             */
            components: components["schemas"]["ScoreComponentResponse"][];
            /** Confidence */
            confidence?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            job: components["schemas"]["JobResponse"];
            /**
             * Matched Skills
             * @default []
             */
            matched_skills: components["schemas"]["SkillResponse"][];
            /**
             * Missing Skills
             * @default []
             */
            missing_skills: components["schemas"]["SkillResponse"][];
            /**
             * Recommendations
             * @default []
             */
            recommendations: string[];
            /** Recruiter Summary */
            recruiter_summary?: string | null;
            /** Score */
            score: number;
        };
        /**
         * ParsedResumeResponse
         * @description One-time parsing response that returns user-submitted source text.
         */
        ParsedResumeResponse: {
            /** Raw Text */
            raw_text: string;
            resume: components["schemas"]["ResumeResponse"];
        };
        /** ProviderFailureResponse */
        ProviderFailureResponse: {
            /**
             * Code
             * @default provider_failed
             */
            code: string;
            /** Provider Name */
            provider_name: string;
        };
        /** RecommendationBatchResponse */
        RecommendationBatchResponse: {
            /** Recommendations */
            recommendations: components["schemas"]["JobRecommendationResponse"][];
        };
        /** RecommendationRequest */
        RecommendationRequest: {
            /** Job Ids */
            job_ids: string[];
            resume: components["schemas"]["ResumeRecommendationInput"];
        };
        /**
         * ResumeRecommendationInput
         * @description User-reviewed resume content accepted by the ranking endpoint.
         */
        ResumeRecommendationInput: {
            /**
             * Achievements
             * @default []
             */
            achievements: string[];
            /**
             * Certifications
             * @default []
             */
            certifications: string[];
            /**
             * Education
             * @default []
             */
            education: string[];
            /** Email */
            email?: string | null;
            /**
             * Experience
             * @default []
             */
            experience: string[];
            /** Github */
            github?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Linkedin */
            linkedin?: string | null;
            /** Name */
            name: string;
            /** Phone */
            phone?: string | null;
            /**
             * Projects
             * @default []
             */
            projects: string[];
            /** Raw Text */
            raw_text: string;
            /**
             * Skills
             * @default []
             */
            skills: components["schemas"]["SkillResponse"][];
        };
        /**
         * ResumeResponse
         * @description Structured resume data safe for ordinary API responses.
         */
        ResumeResponse: {
            /**
             * Achievements
             * @default []
             */
            achievements: string[];
            /**
             * Certifications
             * @default []
             */
            certifications: string[];
            /**
             * Education
             * @default []
             */
            education: string[];
            /** Email */
            email?: string | null;
            /**
             * Experience
             * @default []
             */
            experience: string[];
            /** Github */
            github?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Linkedin */
            linkedin?: string | null;
            /** Name */
            name: string;
            /** Phone */
            phone?: string | null;
            /**
             * Projects
             * @default []
             */
            projects: string[];
            /**
             * Skills
             * @default []
             */
            skills: components["schemas"]["SkillResponse"][];
        };
        /** SaveJobRequest */
        SaveJobRequest: {
            /** Notes */
            notes?: string | null;
        };
        /** SavedJobListResponse */
        SavedJobListResponse: {
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["SavedJobResponse"][];
        };
        /** SavedJobResponse */
        SavedJobResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            job: components["schemas"]["JobResponse"];
            /** Notes */
            notes?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ScoreComponentResponse */
        ScoreComponentResponse: {
            /** Explanation */
            explanation: string;
            /**
             * Matched Skills
             * @default []
             */
            matched_skills: components["schemas"]["SkillResponse"][];
            /**
             * Missing Skills
             * @default []
             */
            missing_skills: components["schemas"]["SkillResponse"][];
            /** Name */
            name: string;
            /** Score */
            score: number;
        };
        /** SkillResponse */
        SkillResponse: {
            /** Category */
            category?: string | null;
            /** Name */
            name: string;
        };
        /** TransitionApplicationRequest */
        TransitionApplicationRequest: {
            /** Next Action */
            next_action?: string | null;
            /** Next Action Due At */
            next_action_due_at?: string | null;
            /** Note */
            note?: string | null;
            status: components["schemas"]["ApplicationStatus"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationIssue */
        ValidationIssue: {
            /** Location */
            location: (string | number)[];
            /** Message */
            message: string;
            /** Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_applications_api_v1_applications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_application_api_v1_applications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApplicationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDetailResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_application_api_v1_applications__application_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDetailResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transition_application_api_v1_applications__application_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionApplicationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDetailResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_account_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticatedUserResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    liveness_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readiness_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    search_jobs_api_v1_jobs_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_search_task_api_v1_jobs_search_tasks_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSearchTaskCreatedResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_search_task_api_v1_jobs_search_tasks__task_id__get: {
        parameters: {
            query?: never;
            header: {
                "X-Task-Token": string;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSearchTaskResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_search_task_api_v1_jobs_search_tasks__task_id__delete: {
        parameters: {
            query?: never;
            header: {
                "X-Task-Token": string;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSearchTaskResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommend_jobs_api_v1_recommendations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationBatchResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_current_resume_api_v1_resumes_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    parse_resume_api_v1_resumes_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_parse_resume_api_v1_resumes_parse_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParsedResumeResponse"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_saved_jobs_api_v1_saved_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedJobListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    save_job_api_v1_saved_jobs__job_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedJobResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_saved_job_api_v1_saved_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
